server:
  host: "0.0.0.0"
  port: 8080

redis:
  enabled: true
  addr: "redis:6379"
  password: ""
  db: 0
  ttl: "3600s"

postgres:
  host: ""
  port: 0
  user: ""
  password: ""
  db: ""
  sslmode: ""
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "5m"